language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-wordpress.gemspec
- gem install sensu-plugins-wordpress-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: C9Xd9GK7bMDRwv7Q75lYW5J0cVufp3Ys8ZU1Kcmll6f695b6MMUkjcmc6qCXlT09MRnPXnb2FyqkM8YZs7j9C2cj/jT9SESyikNsN61wkH5Bx0boonDaEnlYz/mksXHoRMaxHgPNPPTaBxz1SA94+foQHzKQezvraIISsYzNQe4=
  gem: sensu-plugins-wordpress
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-wordpress
